package org.orbisgis.sos;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SpectrumChannel {
    private int subsampling_ratio;
    private int minimum_samples_length;
    private List<BiquadFilter> subSamplers = new ArrayList<>();
    // Cascaded filters are placed here, each element will take less and less samples as input
    private List<HashMap<Integer, BiquadFilter>> iirFilters;
    private DigitalFilter aWeightingFilter = null;
    private DigitalFilter cWeightingFilter = null;
    private int bandFilterSize = 0;

    public SpectrumChannel() {

    }

    private double[] toArray(List<Double> array) {
        double[] retvalue = new double[array.size()];
        for(int i=0; i<retvalue.length; i++) {
            retvalue[i] = array.get(i);
        }
        return retvalue;
    }

    /**
     * Load configuration generated by filterdesign.py
     * @param configuration Filters configuration
     * @param useCascade Reduce computation time by subsampling the audio according to filter frequency range
     */
    public void loadConfiguration(ConfigurationSpectrumChannel configuration, boolean useCascade) {
        if(!configuration.getBandpass().isEmpty()) {
            int maxSubsampling = 0;
            if(useCascade) {
                for (ConfigurationBiquad biquad : configuration.getBandpass()) {
                    maxSubsampling = Math.max(maxSubsampling, biquad.getSubsamplingDepth());
                }
            }
            iirFilters = new ArrayList<>();
            subsampling_ratio = configuration.getAntiAliasing().getSampleRatio();
            minimum_samples_length = (int)Math.pow(subsampling_ratio, maxSubsampling);
            ConfigurationSos filterConf = configuration.getAntiAliasing();
            for(int i = 0; i < maxSubsampling; i++) {
                BiquadFilter filter = new BiquadFilter(toArray(filterConf.getB0()),
                        toArray(filterConf.getB1()),
                        toArray(filterConf.getB2()),
                        toArray(filterConf.getA1()),
                        toArray(filterConf.getA2()));
                subSamplers.add(filter);
            }
            // init cascaded filter storage
            for(int i=0; i <= maxSubsampling; i++) {
                iirFilters.add(new HashMap<Integer, BiquadFilter>());
            }
            // fill cascaded filter instances
            for (int i = 0; i < configuration.getBandpass().size(); i++) {
                bandFilterSize += 1;
                ConfigurationBiquad biquad = configuration.getBandpass().get(i);
                ConfigurationSos refFilter;
                if(useCascade) {
                    refFilter = biquad.getSubsamplingFilter().getSos();
                } else {
                    refFilter = biquad.getSos();
                }
                BiquadFilter filter = new BiquadFilter(toArray(refFilter.getB0()),
                        toArray(refFilter.getB1()),
                        toArray(refFilter.getB2()),
                        toArray(refFilter.getA1()),
                        toArray(refFilter.getA2()));
                if(useCascade) {
                    iirFilters.get(biquad.getSubsamplingDepth()).put(i, filter);
                } else {
                    iirFilters.get(0).put(i, filter);
                }
            }
            if(configuration.getAWeighting() != null) {
                aWeightingFilter = new DigitalFilter(
                        toArray(configuration.getAWeighting().getFilterNumerator()),
                        toArray(configuration.getAWeighting().getFilterDenominator()));
            }
            if(configuration.getCWeighting() != null) {
                cWeightingFilter = new DigitalFilter(
                        toArray(configuration.getCWeighting().getFilterNumerator()),
                        toArray(configuration.getCWeighting().getFilterDenominator()));
            }
        }
    }

    public double processSamplesWeightA(float[] samples) {
        if(aWeightingFilter != null) {
            return aWeightingFilter.filterLeq(samples);
        } else {
            throw new IllegalStateException("A weighting filter not configured");
        }
    }

    public double processSamplesWeightC(float[] samples) {
        if(cWeightingFilter != null) {
            return cWeightingFilter.filterLeq(samples);
        } else {
            throw new IllegalStateException("C weighting filter not configured");
        }
    }

    public double[] processSamples(float[] samples) {
        if(samples.length % minimum_samples_length != 0) {
            throw new IllegalArgumentException(String.format("Provided samples len should be a" +
                    " factor of %d samples", minimum_samples_length));
        }
        if(iirFilters.isEmpty()) {
            throw new IllegalStateException("Loaded configuration does not contain bandpass" +
                    " filters");
        }
        float[] lastFilterSamples = samples;
        double[] leqs = new double[bandFilterSize];
        for (int cascadeIndex=0; cascadeIndex < iirFilters.size(); cascadeIndex++) {
            HashMap<Integer, BiquadFilter> cascadeFilters = iirFilters.get(cascadeIndex);
            for (Map.Entry<Integer, BiquadFilter> filterEntry : cascadeFilters.entrySet()) {
                leqs[filterEntry.getKey()] = filterEntry.getValue().
                        filterThenLeq(lastFilterSamples);
            }
            // subsampling for next iteration
            if(cascadeIndex < subSamplers.size()) {
                float[] nextFilterSamples = new float[lastFilterSamples.length/subsampling_ratio];
                subSamplers.get(cascadeIndex).filterSlice(lastFilterSamples, nextFilterSamples,
                        subsampling_ratio);
                lastFilterSamples = nextFilterSamples;
            }
        }


        return leqs;
    }
}
