# docker-compose build
volumes:
  postgis-data:
    driver: local
  cloudbeaver:
    driver: local
  onomap-data:
    driver: local

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: on-failure
    ports:
      - '8978:8978'
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
      - ./onomap/cloudbeaver/conf:/opt/cloudbeaver/conf
    environment:
      - CLOUDBEAVER_EXPIRE_SESSION_AFTER_PERIOD=1800000
  db:
    container_name: postgis
    image: tobi312/rpi-postgresql-postgis:15-3.5-alpine-arm64
#    build:
#      dockerfile: onomap/postgis/Dockerfile #x64 only
#      #dockerfile: onomap/postgis/Dockerfile_macos_arm64
    user: "${UID}:${GID}"
    volumes:
      - postgis-data:/var/lib/postgresql/data
      - ./:/data
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=noisecapture
      - POSTGRES_USER=onomap
      - POSTGRES_PASSWORD=onomap
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onomap -d noisecapture"]
      interval: 60s
      timeout: 5s
      retries: 5
  onomap:
    build:
      context: ./onomap
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8888:8888"
    volumes:
      - onomap-data:/onomap/workspace/
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - PGHOST=postgis
      - PGDBNAME=noisecapture
      - POSTGRES_USER=onomap
      - POSTGRES_PASSWORD=onomap
      - workingDir=/onomap/workspace/
      # Restrict to small dataset for test purposes (remove theses two lines on production)
      - GADM_URI=https://github.com/Universite-Gustave-Eiffel/NoiseCapture/raw/refs/heads/onomapv2/onomap/src/test/resources/org/noise_planet/onomap/ut_deps.geojson
      - TIMEZONE_URI=https://github.com/Universite-Gustave-Eiffel/NoiseCapture/raw/refs/heads/onomapv2/onomap/src/test/resources/org/noise_planet/onomap/tz_world.shp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s