 -- H2 Only

-- H2GIS only queries

CREATE SPATIAL INDEX ON NOISECAPTURE_POINT(THE_GEOM);
CREATE SPATIAL INDEX ON NOISECAPTURE_AREA(THE_GEOM);
CREATE SPATIAL INDEX ON NOISECAPTURE_AREA_CLUSTER(THE_GEOM);
