[noisecapture]
pg1-path=/var/lib/postgresql/data
pg1-database=noisecapture

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full-type=time
repo1-retention-full=28
repo1-retention-diff=3
start-fast=y

[global:archive-push]
compress-level=3

