name: onomap

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 1.8
      - name: Building
        run: cd onomap-geoserver/geoserver/ && ./gradlew test --info --stacktrace
      - name: Clean
        run: rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
