name: Onomap Web Server

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_USER: onomap
          POSTGRES_PASSWORD: onomap
          POSTGRES_DB: noisecapture
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Building
        run: ./gradlew build -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.http.connectionTimeout=60000 -x test --build-cache --info --stacktrace
        working-directory: onomap
      - name: Test with H2GIS
        run: ./gradlew test --rerun-tasks --info
        working-directory: onomap
      - name: Test with POSTGIS
        run: ./gradlew test --rerun-tasks --info
        working-directory: onomap
        env:
          POSTGRES_HOST: localhost
